"""
Django settings for pgmolstest project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bkm*v8k-^s@$^uoc9&7#y=2!_%)x)lh)iu!n3%2aqn^-4u6kfn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_rdkit',
    'django_extensions',
    'debug_toolbar',
    'rest_framework',
    'generic_relations',
    'django_pdb',
    'flow_battery',
    'guardian',
    'jobs',
    'pgmols',
    'dbmover',
    # 'wcgrid',
    'molgen',
    'restapi'
    ]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

MIDDLEWARE_CLASSES = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_pdb.middleware.PdbMiddleware'
]

ROOT_URLCONF = 'djangochem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangochem.wsgi.application'


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'guardian.backends.ObjectPermissionBackend',
)


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

# Settings for wcgrid:

JOB_GROUPS = {
    'small': {
        'templates': [
            'bp86.svp.n.opt.in',
            'bp86.svp.n.bp86.svp.n.sp.in',
            'bp86.svp.n.b3lyp.svp.n.sp.in',
            'bp86.svp.n.pbe0.svp.n.sp.in',
        ],
    },
    'medium': {
        'templates': [
            'bp86.svp.n.opt.in',
            'bp86.svp.n.b3lyp.svp.n.sp.in',
            'bp86.svp.n.bp86.svp.n.sp.in',
            'bp86.svp.n.m062x.svp.n.sp.in',
            'bp86.svp.n.pbe0.svp.n.sp.in',
            'bp86.svp.n.upbe0.svp.n.sp.in',
            'bp86.svp.n.bp86.tzvp.n.sp.in',
            'bp86.svp.n.b3lyp.tzvp.n.sp.in',
        ],
    },
    'large': {
        'templates': [
            'noopt.bp86.sto6g.n.sp.in',
            'noopt.bp86.svp.n.sp.in',
            'bp86.svp.n.opt.in',
            'bp86.svp.n.b3lyp.svp.n.sp.in',
            'bp86.svp.n.bhandhlyp.svp.n.sp.in',
            'bp86.svp.n.bp86.svp.n.sp.in',
            'bp86.svp.n.hf.svp.n.sp.in',
            'bp86.svp.n.m062x.svp.n.sp.in',
            'bp86.svp.n.pbe0.svp.n.sp.in',
            'bp86.svp.n.uhf.svp.n.sp.in',
            'bp86.svp.n.um062x.svp.n.sp.in',
            'bp86.svp.n.upbe0.svp.n.sp.in',
            'bp86.svp.n.b3lyp.tzvp.n.sp.in',
            'bp86.svp.n.bp86.tzvp.n.sp.in',
            'bp86.svp.n.pbe0.tzvp.n.sp.in',
            'bp86.svp.n.upbe0.tzvp.n.sp.in',
        ]
    },
    'xl': {
        'templates': [
            'bp86.svp.n.b3lyp.svp.n.sp.in',
            'bp86.svp.n.b3lyp.tzvp.n.sp.in',
            'bp86.svp.n.bp86.svp.n.sp.in',
            'bp86.svp.n.bp86.tzvp.n.sp.in',
            'bp86.svp.n.opt.in',
        ],
        'common_template_params': {
            'MEM_STATIC': 94,
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_COLLAPSED': True
}

LOGIN_DEFAULT_URL = "/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'django-debug.log',
        },
        'parser_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'jobdirparser.log',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'jobdirparser': {
            'handlers': ['parser_file'],
            'level': 'DEBUG',
            'propagate': True,
        },

    },
}
