# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 18:06
from __future__ import unicode_literals

from django.db import migrations
from psycopg2.extensions import AsIs
from pgmols.models import Calc

class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0006_auto_20160412_1805'),
    ]

    operations = [
        migrations.RunSQL(
            [("CREATE INDEX calc_props_gin ON %s USING gin"
                "(props);", [AsIs(Calc._meta.db_table)])],
            [('DROP INDEX calc_props_gin;', None)],
        )
    ]
