# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0007_auto_20160412_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
