# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0008_geom_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='mol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calcs', to='pgmols.Mol'),
        ),
    ]
