# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0009_auto_20160621_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mol',
            name='smiles',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
