# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0010_auto_20160707_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mol',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
