# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgmols', '0012_auto_20160719_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='props',
            new_name='details',
        ),
        migrations.AddField(
            model_name='calc',
            name='reaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calcs', to='pgmols.Reaction'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='geoms',
            field=models.ManyToManyField(related_name='calcs', to='pgmols.Geom'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='mol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calcs', to='pgmols.Mol'),
        ),
    ]
