# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=24)),
                ('duration', models.FloatField(null=True)),
                ('cores', models.IntegerField(null=True)),
                ('architecture', models.CharField(max_length=24, null=True)),
                ('repoversion', models.CharField(max_length=24, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('completetime', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(default=0)),
                ('parentid', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('configpath', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobConfig'),
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='job',
            name='parentct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childjob', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='job',
            name='workbatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.WorkBatch'),
        ),
    ]
