# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatch',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
