# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_workbatch_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('claimed', 'Claimed'), ('done', 'Done'), ('error', 'Error')], default='', max_length=24),
        ),
    ]
