# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160621_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobconfig',
            name='parent_class_name',
            field=models.CharField(choices=[('Mol', 'Mol'), ('Geom', 'Geom'), ('Calc', 'Calc')], default='Geom', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('claimed', 'Claimed'), ('done', 'Done'), ('error', 'Error'), ('', 'None')], default='', max_length=24),
        ),
    ]
