# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160629_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('claimed', 'Claimed'), ('done', 'Done'), ('error', 'Error'), ('', 'None')], db_index=True, default='', max_length=24),
        ),
    ]
