# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160713_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),

    ]
