# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:17
from __future__ import unicode_literals

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Job = apps.get_model('jobs', 'job')
    for row in Job.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_uuid'),
    ]

    operations = [
     # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
